define(
	["jquery", "backbone",
	 "hbs!templates/downloaddialog"],

	function($, Backbone, dialogTemplate) {

		var DownloadDialog = Backbone.View.extend({

			constructor: function DownloadDialog() {
				Backbone.View.prototype.constructor.apply(this, arguments);
			},

			// tag,ID for the autogenerated node the view will be enclosed in
			tagName: "div",
			id: "downloadDialog",

			url: null,
			filename: null,

			events: {
				"click #btnCancel": "close",
			},

			initialize: function(options) {

				this.url = options.url || "";
				this.filename = options.filename || "<n/a>";

				this.render();
			},

			// create the dialog nodes and insert into page DOM
			render: function() {

				var context = {
					href: this.url,
					filename : this.filename,
				};
				this.$el.html(dialogTemplate(context));
				$(document.body).append(this.$el);

				return this;
			},

			close: function() {

				// If we are replacing a previously generated file we need to
				// manually revoke the object URL to avoid memory leaks.
				if (this.url !== null) {
					window.URL.revokeObjectURL(this.url);
					this.url = null;
				}

				this.trigger("dialog:cancel");
				this.remove();
			},
		});

		return DownloadDialog;
	}
);
