define(
	["jquery", "backbone",
	 "models/settings",
	 "hbs!templates/settingsdialog"],

	function($, Backbone, Settings, dialogTemplate) {

		var SettingsDialog = Backbone.View.extend({

			// tag,ID for the autogenerated node the view will be enclosed in
			tagName: "div",
			id: "settingsdialog",

			/** @type {Settings} the settings model */
			model: null,

			$probMobilityInput: null,
			$probIndoorInput: null,
			$confidenceThresholdInput: null,
			$checkUseDotIcons: null,
			$softHeatmapThresholdInput: null,
			$hardHeatmapThresholdInput: null,

			events: {
				"click #btnApply": "applyClicked",
				"click #btnCancel": "close",
				"click #btnReset": "resetSettings",
			},

			initialize: function() {

				this.listenTo(this.model, "reset", this.updateControls);

				this.render();
				this.updateControls();
			},

			// create the dialog nodes and insert into page DOM
			render: function() {

				this.$el.html(dialogTemplate());
				$(document.body).append(this.$el);

				this.$probMobilityInput = this.$("#probMobilityInput");
				this.$probIndoorInput = this.$("#probIndoorInput");
				this.$confidenceThresholdInput = this.$("#confidenceThresholdInput");

				this.$softHeatmapThresholdInput = this.$("#softHeatmapThresholdInput");
				this.$hardHeatmapThresholdInput = this.$("#hardHeatmapThresholdInput");

				this.$checkUseDotIcons = this.$("#checkUseDotIcons");

				return this;
			},

			// set the controls to the current model values
			updateControls: function() {

				this.$probMobilityInput.val(toPercent(this.model.get("mobilityThreshold")));
				this.$probIndoorInput.val(toPercent(this.model.get("indoorThreshold")));
				this.$confidenceThresholdInput.val(toPercent(this.model.get("confidenceThreshold")));

				this.$softHeatmapThresholdInput.val(this.model.get("heatmapSuggestionThreshold"));
				this.$hardHeatmapThresholdInput.val(this.model.get("maxResultMarkers"));

				this.$checkUseDotIcons.prop("checked", this.model.get("useDotAccuracyMarkers"));
			},

			/**
			 * Handler for the "Reset" button in the dialog.
			 */
			resetSettings: function() {

				if (confirm("This will revert all settings to their defaults..."))
					this.model.reset();
			},

			applyClicked: function() {

				var probMobility = parseFloat(this.$probMobilityInput.val()),
					probIndoor = parseFloat(this.$probIndoorInput.val()),
					confThreshold = parseFloat(this.$confidenceThresholdInput.val()),
					heatmapSoftThreshold = parseInt(this.$softHeatmapThresholdInput.val(), 10),
					heatmapHardThreshold = parseInt(this.$hardHeatmapThresholdInput.val(), 10),
					useDotIcons = this.$checkUseDotIcons.prop("checked");

				this.model.set({
					mobilityThreshold: fromPercent(probMobility),
					indoorThreshold: fromPercent(probIndoor),
					confidenceThreshold: fromPercent(confThreshold),
					maxResultMarkers: heatmapHardThreshold,
					heatmapSuggestionThreshold: heatmapSoftThreshold,
					useDotAccuracyMarkers: useDotIcons,
				});

				this.trigger("dialog:apply");
				this.remove();
			},

			close: function() {

				this.trigger("dialog:cancel");
				this.remove();
			},
		});

		function toPercent(val) {
			return val * 100.0;
		}

		function fromPercent(val) {
			return val / 100.0;
		}

		return SettingsDialog;
	}
);
