define(
	["jquery", "backbone",
	 "types/viewport",
	 "hbs!../../templates/viewportdialog"],

	function($, Backbone, Viewport, dialogTemplate) {

		var ViewportDialog = Backbone.View.extend({

			// tag,ID for the autogenerated node the view will be enclosed in
			tagName: "div",
			id: "viewportDialog",

			/** @type {Viewport} the viewport model */
			viewport: null,

			events: {
				"click #btnApply": "applyClicked",
				"click #btnCancel": "close",
			},

			initialize: function() {

				this.viewport = this.options.viewport || new Viewport();

				this.render();
				this.updateControls();
			},

			// create the dialog nodes and insert into page DOM
			render: function() {

				this.$el.html(dialogTemplate());
				$(document.body).append(this.$el);

				return this;
			},

			// set the controls to the current model values
			updateControls: function() {

				if (this.viewport.isValid()) {
					this.$("#centerInput").val(this.viewport.center.toUrlValue());
					this.$("#zoomInput").val(this.viewport.zoom);
					this.$("#boundsInput")
						.val(this.viewport.serialize())
						.focus();
				}
			},

			applyClicked: function() {

				var input = $("#boundsInput").val();
				this.viewport.parse(input);

				this.trigger("viewport:set", this.viewport);
				this.remove();
			},

			close: function() {

				this.trigger("dialog:cancel");
				this.remove();
			},
		});

		return ViewportDialog;
	}
);
